
version: '3.5'

services:

  redis:
    image: redis:latest
    volumes:
      - redis:/redis
    ports:
      - 6379:6379

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-tech}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-tech_passwd}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./src/main/resources/db/migration/init:/docker-entrypoint-initdb.d  # Mapeie o diretório de migrações para dentro do contêiner
    ports:
      - "5432:5432"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  redis:
  postgres:
  pgadmin: