application:
  title: 3soat-tech_challenge
  version: 1.0.0

springdoc:
  swagger-ui:
    use-root-path: true
    disable-swagger-default-url: true
    path: /swagger-ui.html
  packagesToScan: br.com.tech.challenge.api

spring:
  data:
    redis:
      port: 6379
      host: localhost
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tech_challenge
    hikari:
      username: limite
      password: limite_passwd
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
      use_jdbc_metadata_defaults: false

